version: '3.9'

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents node_modules overwrite
    working_dir: /app
    command: npm run dev -- --host
